image: node:10.6.0

stages:
  - test_backend
  - build_frontend
  - test_frontend
  - build_backend
  - sonarqube

build site frontend:
  image: node:6
  stage: build_frontend
  script:
    - cd webshop-client
    - npm install
    - npm run build

unit test backend:
  stage: test_backend
  script:
    - gradlew check

sonarqube:
  stage: sonarqube
  script:
    - ls
    - .\gradlew sonarqube
