image: node:10.6.0

stages:
  - sonarqube
  - build
  - test

cache:
  paths:
    - node_modules/

build site:
  stage: build
  script:
    - npm install --progress=false
    - npm run build

unit test:
  stage: test
  script:
    - npm test
  artifacts:
    paths:
      - dist/
      - node_modules/
      - package.json

sonarqube:
  stage: sonarqube
  script:
    - cd /webshop-service/
    - ./gradlew sonarqube