image: node:10.6.0

stages:
  - build_backend
  - test_backend
  - build_frontend
  - test_frontend
  - sonarqube

build site backend:
  stage: build_backend
  script:
    - cd webshop-service
    - ./gradlew build

unit test backend:
  stage: test_backend
  script:
    - cd webshop-service
    - ./gradlew check

build site frontend:
  image: node:6
  stage: build_frontend
  script:
    - cd webshop-client
    - npm install
    - npm run build


sonarqube:
  stage: sonarqube
  script:
    - cd webshop-service
    - .\gradlew sonarqube
