image: node:10.6.0

stages:
  - build_frontend
  - test_frontend
  - build_backend
  - test_backend
  - sonarqube

build site frontend:
  image: node:6
  stage: build_frontend
  script:
    - cd webshop-client
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

build site backend:
  stage: build_backend
  script:
    - cd ..
    - cd webshop-service
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

unit test backend:
  stage: test_backend
  script:
    - ./gradlew check

sonarqube:
  stage: sonarqube
  script:
    - ls
    - .\gradlew sonarqube
